"""add commands and actions tables

Revision ID: 4297ffdc48f2
Revises:
Create Date: 2025-08-10 20:36:26.425723

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4297ffdc48f2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "commands",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("command", sa.TEXT(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED", "RUNNING", "COMPLETED", "FAILED", "WITHDRAWN", name="statuses"
            ),
            nullable=False,
        ),
        sa.Column("created", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "actions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("command_id", sa.UUID(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "MOVE_FORWARD",
                "MOVE_BACKWARD",
                "ROTATE_LEFT",
                "ROTATE_RIGHT",
                name="actiontypes",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED", "RUNNING", "COMPLETED", "FAILED", "WITHDRAWN", name="statuses"
            ),
            nullable=False,
        ),
        sa.Column("x_coord", sa.Integer(), nullable=True),
        sa.Column("y_coord", sa.Integer(), nullable=True),
        sa.Column(
            "direction",
            sa.Enum("NORTH", "SOUTH", "WEST", "EAST", name="directions"),
            nullable=True,
        ),
        sa.Column("created", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(["command_id"], ["commands.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("actions")
    op.drop_table("commands")
    # ### end Alembic commands ###
